/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.Gestion_Cafeteria;
import Modelo.Cafeteria;
import Modelo.Patron_Command.Command;
import Modelo.Patron_Command.Gestor_Command;
import Modelo.Patron_Command.Pedido;
import Modelo.Patron_Command.Pedido_Listo;
import Modelo.Patron_Command.Preparar_Pedido;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Alonso
 */
public class Pantallita extends javax.swing.JFrame {

    /**
     * Creates new form Pantallita
     */
    public Pantallita() {
        initComponents();
    }
    Gestion_Cafeteria gestion = Gestion_Cafeteria.getInstancia();  //Singleton.
    Pedido pedido = new Pedido();
    Gestor_Command comando = new Gestor_Command();  //Command.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_NumPedido = new javax.swing.JLabel();
        lbl_Cafe = new javax.swing.JLabel();
        lbl_Precio = new javax.swing.JLabel();
        txt_NumPedido = new javax.swing.JTextField();
        cbx_Cafe = new javax.swing.JComboBox<>();
        txt_Precio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        lbl_Titulo = new javax.swing.JLabel();
        chk_Azucar = new javax.swing.JCheckBox();
        chk_Canela = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        lbl_Azucar = new javax.swing.JLabel();
        lbl_Canela = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        lbl_DineroTotal = new javax.swing.JLabel();
        txt_DineroTotal = new javax.swing.JTextField();
        btnPreparar = new javax.swing.JButton();
        txt_Estado = new javax.swing.JTextField();
        btnListo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lbl_NumPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NumPedido.setText("Número de pedido:");
        jPanel1.add(lbl_NumPedido);
        lbl_NumPedido.setBounds(43, 126, 164, 25);

        lbl_Cafe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Cafe.setText("Tipos de Café:");
        jPanel1.add(lbl_Cafe);
        lbl_Cafe.setBounds(43, 194, 120, 25);

        lbl_Precio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Precio.setText("Precio:");
        jPanel1.add(lbl_Precio);
        lbl_Precio.setBounds(60, 450, 58, 25);

        txt_NumPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_NumPedido);
        txt_NumPedido.setBounds(225, 123, 81, 31);

        cbx_Cafe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbx_Cafe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el de tu agrado :D", "Americano", "Esspreso", "Mocha", "Cappuccino", "Flat White", "Frapuccino", "Café con leche", "Café Irlandés", "Cold Brew", "Affogato" }));
        cbx_Cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_CafeActionPerformed(evt);
            }
        });
        jPanel1.add(cbx_Cafe);
        cbx_Cafe.setBounds(181, 191, 290, 31);

        txt_Precio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_Precio);
        txt_Precio.setBounds(130, 450, 92, 31);

        btnAgregar.setBackground(new java.awt.Color(153, 102, 0));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar Pedido");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(580, 470, 163, 32);

        lbl_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(153, 102, 0));
        lbl_Titulo.setText("Cafetería");
        jPanel1.add(lbl_Titulo);
        lbl_Titulo.setBounds(430, 10, 252, 81);

        chk_Azucar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk_Azucar.setText("Azúcar");
        chk_Azucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_AzucarActionPerformed(evt);
            }
        });
        jPanel1.add(chk_Azucar);
        chk_Azucar.setBounds(61, 316, 82, 29);

        chk_Canela.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chk_Canela.setText("Canela");
        chk_Canela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_CanelaActionPerformed(evt);
            }
        });
        jPanel1.add(chk_Canela);
        chk_Canela.setBounds(61, 363, 80, 29);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ingredientes extra:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(43, 273, 161, 25);

        lbl_Azucar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_Azucar.setText("+ 0.50");
        jPanel1.add(lbl_Azucar);
        lbl_Azucar.setBounds(172, 318, 53, 25);

        lbl_Canela.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_Canela.setText("+ 0.75");
        jPanel1.add(lbl_Canela);
        lbl_Canela.setBounds(172, 365, 53, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alonso\\Downloads\\fondo-de-hojas-de-otono-dibujadas-mano\\5690635.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 600);

        jTabbedPane1.addTab("Pedidos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));
        jPanel2.setLayout(null);

        tablita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Pedido", "Café", "Precio Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablita);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(6, 170, 885, 311);

        btnMostrar.setBackground(new java.awt.Color(153, 102, 0));
        btnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnMostrar);
        btnMostrar.setBounds(462, 508, 305, 32);

        lbl_DineroTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_DineroTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DineroTotal.setText("Dinero recaudado:");
        jPanel2.add(lbl_DineroTotal);
        lbl_DineroTotal.setBounds(31, 546, 157, 25);

        txt_DineroTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(txt_DineroTotal);
        txt_DineroTotal.setBounds(194, 543, 170, 31);

        btnPreparar.setBackground(new java.awt.Color(153, 102, 0));
        btnPreparar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPreparar.setForeground(new java.awt.Color(255, 255, 255));
        btnPreparar.setText("Preparar café");
        btnPreparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepararActionPerformed(evt);
            }
        });
        jPanel2.add(btnPreparar);
        btnPreparar.setBounds(22, 35, 144, 32);

        txt_Estado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(txt_Estado);
        txt_Estado.setBounds(184, 35, 437, 31);

        btnListo.setBackground(new java.awt.Color(153, 102, 0));
        btnListo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListo.setForeground(new java.awt.Color(255, 255, 255));
        btnListo.setText("Listo");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        jPanel2.add(btnListo);
        btnListo.setBounds(22, 93, 72, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alonso\\Downloads\\coffee-cafe-beverage-seamless-pattern-dark-background-vector.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 600);

        jTabbedPane1.addTab("Lista dePedidos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int num_pedido = Integer.parseInt(txt_NumPedido.getText());
        String tipo_cafe = cbx_Cafe.getSelectedItem().toString();
        double precio = Double.parseDouble(txt_Precio.getText());
        Cafeteria cafee = new Cafeteria(tipo_cafe);
        cafee.setNum_pedido(num_pedido);
        cafee.setPrecio(precio);
        
        String mensaje = "Está seguro de pedir "+tipo_cafe+"?";
        int opcion = JOptionPane.showConfirmDialog(this, mensaje, "Resgistrar pedido",JOptionPane.YES_NO_OPTION);
        if(opcion == 0){  //Si la respuesta es SI (0)
            String msj_si = "Pedido registrado :)";
            JOptionPane.showMessageDialog(this, msj_si);
            gestion.agregar_Pedido(cafee);  //Como la respuesta es afirmativa se agrega el pedido.
            txt_NumPedido.setText("");
            cbx_Cafe.setSelectedIndex(0);
            txt_Precio.setText("");
            chk_Azucar.setSelected(false);
            chk_Canela.setSelected(false);
        }else{
            String msj_no = "Pedido cancelado.";  //Si la respuesta es NO (1), se cancela y no pasa nada.
            JOptionPane.showMessageDialog(this, msj_no);
            cbx_Cafe.setSelectedIndex(0);
            txt_Precio.setText("");
            chk_Azucar.setSelected(false);
            chk_Canela.setSelected(false);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        gestion.mostrar_Pedidos(tablita);
        txt_Estado.setText("");
        txt_Estado.setText("");
        double suma = gestion.dinero_Recaudado(); 
        txt_DineroTotal.setText("S/."+suma);  //Muestra el dinero recaudado.
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void cbx_CafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_CafeActionPerformed
        // TODO add your handling code here:
        String tipo_cafe = (String) cbx_Cafe.getSelectedItem().toString();
        double precio = gestion.obtener_Precio(tipo_cafe);
        txt_Precio.setText(String.valueOf(precio));  //El precio se actualiza automáticamente a la hora de elegir el café.
        
        //Precios actualizados con los CheckBox:
        double precio_Base = gestion.obtener_Precio(cbx_Cafe.getSelectedItem().toString());
        double precio_Final = precio_Base;
        if(chk_Azucar.isSelected()){  //Dependiendo que ingrediente escojas se le suma al precio.
            precio_Final += 0.50;
        }
        if(chk_Canela.isSelected()){
            precio_Final += 0.75;
        }
        txt_Precio.setText(String.format("%.2f", precio_Final));  //Esto va acumulando el dinero obtenido.  %.2f --> 2 decimales luego del entero.
    }//GEN-LAST:event_cbx_CafeActionPerformed

    private void chk_AzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_AzucarActionPerformed
        // TODO add your handling code here:
        cbx_CafeActionPerformed(null);
    }//GEN-LAST:event_chk_AzucarActionPerformed

    private void chk_CanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_CanelaActionPerformed
        // TODO add your handling code here:
        cbx_CafeActionPerformed(null);
    }//GEN-LAST:event_chk_CanelaActionPerformed

    private void btnPrepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepararActionPerformed
        // TODO add your handling code here:
        Command preparar = new Preparar_Pedido(pedido);
        comando.setComando(preparar);
        comando.presionar_Boton();
        txt_Estado.setText(pedido.prepararPedido());  //Coloca el mensaje correspondiente.
    }//GEN-LAST:event_btnPrepararActionPerformed

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
        Command terminado = new Pedido_Listo(pedido);
        comando.setComando(terminado);
        comando.presionar_Boton();
        txt_Estado.setText(pedido.pedidoListo());  //Coloca el mensaje correspondiente.
    }//GEN-LAST:event_btnListoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantallita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantallita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantallita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantallita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantallita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPreparar;
    private javax.swing.JComboBox<String> cbx_Cafe;
    private javax.swing.JCheckBox chk_Azucar;
    private javax.swing.JCheckBox chk_Canela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_Azucar;
    private javax.swing.JLabel lbl_Cafe;
    private javax.swing.JLabel lbl_Canela;
    private javax.swing.JLabel lbl_DineroTotal;
    private javax.swing.JLabel lbl_NumPedido;
    private javax.swing.JLabel lbl_Precio;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JTable tablita;
    private javax.swing.JTextField txt_DineroTotal;
    private javax.swing.JTextField txt_Estado;
    private javax.swing.JTextField txt_NumPedido;
    private javax.swing.JTextField txt_Precio;
    // End of variables declaration//GEN-END:variables
}
